/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "STD_TYPES.h"
#include "BIT_MATH.h"

#include "RCC_interface.h"
#include "DIO_int.h"

#include "FreeRTOS.h"
#include "task.h"
#include  "UART_interface.h"
#include  "GSM_interface.h"
#include   "GPS.h"

u8		URL_CMD[MAX_URL_LENGTH] = {0};
u8		timestampp[12]		 =   "1691123033";
u8		latt[12]			 =   "29.297177";
u8		longg[12]			 =   "30.94329";
u8		speedd[5]			 =   "60";
u8		statuss[5]			 =   "3";
u8	    Data[120]		     =   "{\"fields\": {\"key\": {\"stringValue\": \"key\"}, \"value\": {\"stringValue\": \"1691123033,29.97177,30.94329\"}}}\r\n";
u8		teem = 0;


extern GPS_Frames GPS;



TaskHandle_t	xGSM_TaskHandle;
TaskHandle_t	xGPS_TaskHandle;

void	GSM_Task(void * pvParametrs);
void	GPS_Task(void * pvParametrs);

int main(void)
{
	MRCC_voidSysClkInit();
	/*	1- Enable Per Clk "RCC" Port A		*/
	MRCC_voidEnablePerClk(RCC_APB2,2);
	//enable Rcc for portb
	MRCC_voidEnablePerClk(RCC_APB2,3);
	//enable Rcc for uart1
	MRCC_voidEnablePerClk(RCC_APB2,14);

	//enable Rcc for uart2
		MRCC_voidEnablePerClk(RCC_APB1,17);
	//enable Rcc for uart3
	MRCC_voidEnablePerClk(RCC_APB1,18);


	//PINS for uart1
	/*	Direction for PA9 is output AF */
	M_GPIO_void_SetPinDir(PORTA_ID, PIN9_ID, OUT_50MHZ_AF_PP);
	M_GPIO_void_SetPinDir(PORTA_ID, PIN10_ID, IN_FLOATING);
	//PINS for uart2
	M_GPIO_void_SetPinDir(PORTA_ID, PIN2_ID, OUT_50MHZ_AF_PP);
	M_GPIO_void_SetPinDir(PORTA_ID, PIN3_ID, IN_FLOATING);
	//PINS for uart3
	M_GPIO_void_SetPinDir(PORTB_ID, PIN10_ID, OUT_50MHZ_AF_PP);
	M_GPIO_void_SetPinDir(PORTB_ID, PIN11_ID, IN_FLOATING);

	MUSART1_voidInit();
	MUSART2_voidInit();

	//GSM INIT
		GSM_FireBase_URL_Init(URL_CMD);
		GSM_GPRS_INIT();


	//M_GPIO_void_SetPinDir(PORTA_ID, PIN1_ID, OUT_50MHZ_PP);
	//M_GPIO_void_SetPinDir(PORTA_ID, PIN2_ID, OUT_50MHZ_PP);



	xTaskCreate(GSM_Task, "GSM_Task", 128,NULL,1,&xGSM_TaskHandle);
	xTaskCreate(GPS_Task, "GPS_Task", 128,NULL,1,&xGPS_TaskHandle);

	vTaskStartScheduler();
	/* Loop forever */
	for(;;);
}
void	GSM_Task(void * pvParametrs)
{
	for(;;)
	{
		// MUSART2_voidSendChar('5');
		 GSM_PrepareAndSendData(URL_CMD,GPS.Time,GPS.Longitude,GPS.Latitude,speedd,statuss);

		vTaskDelay(25000);

	}

}
void	GPS_Task(void * pvParametrs)
{
	for(;;)
	{
//RECEIVE from gps and process data to time_stamp,Longitude,Latitude.
		GPS_Update();
		vTaskDelay(1000);
	}
}
